// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcstzgL_3fMlRd0_cHG_svUGhWwJjYetE',
    appId: '1:664420294504:web:111fb6b08719aaa67680dd',
    messagingSenderId: '664420294504',
    projectId: 'dating-app-notification-ec341',
    authDomain: 'dating-app-notification-ec341.firebaseapp.com',
    storageBucket: 'dating-app-notification-ec341.firebasestorage.app',
    measurementId: 'G-4PRR0PSXRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5z3_5sRycWCbdR-0LLrEAYOusr02SxKE',
    appId: '1:664420294504:android:2501466c36db150b7680dd',
    messagingSenderId: '664420294504',
    projectId: 'dating-app-notification-ec341',
    storageBucket: 'dating-app-notification-ec341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0hwxshC7UPlFgCV-zQfZd08zmURQnRg',
    appId: '1:664420294504:ios:3d9bdfa1b37a54277680dd',
    messagingSenderId: '664420294504',
    projectId: 'dating-app-notification-ec341',
    storageBucket: 'dating-app-notification-ec341.firebasestorage.app',
    iosBundleId: 'com.cozune.app',
  );
}
